#!/bin/bash
# Create system directory structure for C4 model documentation
#
# Usage: create-folders.sh <system-name> [base-path]
#
# Exit codes:
#   0 - Success
#   1 - Error (invalid input or filesystem error)

set -euo pipefail

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

error() {
    echo -e "${RED}[CREATE-FOLDERS] ERROR: $1${NC}" >&2
}

success() {
    echo -e "${GREEN}[CREATE-FOLDERS] $1${NC}" >&2
}

warning() {
    echo -e "${YELLOW}[CREATE-FOLDERS] WARNING: $1${NC}" >&2
}

# Check arguments
if [ $# -lt 1 ]; then
    error "Missing required argument: system-name"
    echo "Usage: $0 <system-name> [base-path]" >&2
    exit 1
fi

SYSTEM_NAME="$1"
BASE_PATH="${2:-knowledge-base/systems}"

# Validate system name (kebab-case pattern)
if ! echo "$SYSTEM_NAME" | grep -Eq '^[a-z0-9]+(-[a-z0-9]+)*$'; then
    error "Invalid system name: $SYSTEM_NAME"
    echo "  Expected: kebab-case format (e.g., 'my-system', 'api-gateway')" >&2
    exit 1
fi

# Resolve base path
if [ ! -d "$BASE_PATH" ]; then
    # Try to create base path
    if ! mkdir -p "$BASE_PATH" 2>/dev/null; then
        error "Base path does not exist and cannot be created: $BASE_PATH"
        exit 1
    fi
    success "Created base directory: $BASE_PATH"
fi

# Check if base path is writable
if [ ! -w "$BASE_PATH" ]; then
    error "Base path is not writable: $BASE_PATH"
    exit 1
fi

# Construct system path
SYSTEM_PATH="$BASE_PATH/$SYSTEM_NAME"

# Check if system folder already exists
if [ -d "$SYSTEM_PATH" ]; then
    warning "System folder already exists: $SYSTEM_PATH"
    warning "Skipping creation (no changes made)"
    exit 0
fi

# Create directory structure
echo "[CREATE-FOLDERS] Creating directory structure for system: $SYSTEM_NAME" >&2

mkdir -p "$SYSTEM_PATH/c1" || {
    error "Failed to create c1 directory"
    exit 1
}

mkdir -p "$SYSTEM_PATH/c2" || {
    error "Failed to create c2 directory"
    exit 1
}

mkdir -p "$SYSTEM_PATH/c3" || {
    error "Failed to create c3 directory"
    exit 1
}

mkdir -p "$SYSTEM_PATH/c4" || {
    error "Failed to create c4 directory"
    exit 1
}

# Create README.md
cat > "$SYSTEM_PATH/README.md" <<EOF
# $SYSTEM_NAME

## Overview

This directory contains C4 model documentation for the **$SYSTEM_NAME** system.

## Structure

- \`c1/\` - System Context level documentation
- \`c2/\` - Container level documentation
- \`c3/\` - Component level documentation
- \`c4/\` - Code level documentation (optional)

## Generated Files

All files in this directory are automatically generated by the Melly C4 workflow.

## Last Updated

$(date -u +"%Y-%m-%dT%H:%M:%SZ")
EOF

success "Created directory structure:"
echo "  $SYSTEM_PATH/" >&2
echo "  ├── c1/" >&2
echo "  ├── c2/" >&2
echo "  ├── c3/" >&2
echo "  ├── c4/" >&2
echo "  └── README.md" >&2

success "System folder created successfully"
exit 0
